services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ifx_vm_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=ifx_vm_super_secret_jwt_key_2026
    volumes:
      - db_data:/app/DB
    networks:
      - ifx-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ifx_vm_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ifx-network

volumes:
  db_data:
    name: ifx_vm_db_data

networks:
  ifx-network:
    driver: bridge
